from src.utils.DofusMapEnum import DofusMap
from src.utils.Square import Square
from src.utils.RESOURCES import CEREAL
from src.utils.RESOURCES import FISH
from src.utils.RESOURCES import FLOWER
from src.utils.RESOURCES import RESOURCES
from src.utils.RESOURCES import ORE
from src.utils.RESOURCES import WOOD

Ecaflipus = {
	'-9,-22': Square(x=-9, y=-22, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-9, -23)', '(-8, -22)', '(-9, -21)', '(-10, -22)'], resources=[], specialSquares=[]),
	'-9,-21': Square(x=-9, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-9, -22)', '(-8, -21)', '(-9, -20)', '(-10, -21)'], resources=[], specialSquares=[]),
	'-9,-20': Square(x=-9, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-9, -21)', '(-8, -20)', '(-9, -19)', '(-10, -20)'], resources=[], specialSquares=[]),
	'-9,-19': Square(x=-9, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-9, -20)', '(-8, -19)', '(-9, -18)', '(-10, -19)'], resources=[], specialSquares=[]),
	'-9,-10': Square(x=-9, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-9, -11)', '(-8, -10)', '(-9, -9)', '(-10, -10)'], resources=[], specialSquares=[]),
	'-9,-2': Square(x=-9, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-9, -3)', '(-8, -2)', '(-9, -1)', '(-10, -2)'], resources=[], specialSquares=[]),
	'-13,-21': Square(x=-13, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-13, -22)', '(-12, -21)', '(-13, -20)', '(-14, -21)'], resources=[], specialSquares=[]),
	'-13,-19': Square(x=-13, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-13, -20)', '(-12, -19)', '(-13, -18)', '(-14, -19)'], resources=[], specialSquares=[]),
	'-13,-18': Square(x=-13, y=-18, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-13, -19)', '(-12, -18)', '(-13, -17)', '(-14, -18)'], resources=[], specialSquares=[]),
	'-10,-22': Square(x=-10, y=-22, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-10, -23)', '(-9, -22)', '(-10, -21)', '(-11, -22)'], resources=[], specialSquares=[]),
	'-10,-21': Square(x=-10, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-10, -22)', '(-9, -21)', '(-10, -20)', '(-11, -21)'], resources=[], specialSquares=[]),
	'-10,-20': Square(x=-10, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-10, -21)', '(-9, -20)', '(-10, -19)', '(-11, -20)'], resources=[], specialSquares=[]),
	'-10,-19': Square(x=-10, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-10, -20)', '(-9, -19)', '(-10, -18)', '(-11, -19)'], resources=[], specialSquares=[]),
	'-10,-11': Square(x=-10, y=-11, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-10, -12)', '(-9, -11)', '(-10, -10)', '(-11, -11)'], resources=[], specialSquares=[]),
	'-3,-8': Square(x=-3, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-3, -9)', '(-2, -8)', '(-3, -7)', '(-4, -8)'], resources=[], specialSquares=[]),
	'-3,-6': Square(x=-3, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-3, -7)', '(-2, -6)', '(-3, -5)', '(-4, -6)'], resources=[], specialSquares=[]),
	'-4,-8': Square(x=-4, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-4, -9)', '(-3, -8)', '(-4, -7)', '(-5, -8)'], resources=[], specialSquares=[]),
	'1,-8': Square(x=1, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, -9)', '(2, -8)', '(1, -7)', '(0, -8)'], resources=[], specialSquares=[]),
	'1,-5': Square(x=1, y=-5, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, -6)', '(2, -5)', '(1, -4)', '(0, -5)'], resources=[], specialSquares=[]),
	'1,-3': Square(x=1, y=-3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, -4)', '(2, -3)', '(1, -2)', '(0, -3)'], resources=[], specialSquares=[]),
	'1,-2': Square(x=1, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, -3)', '(2, -2)', '(1, -1)', '(0, -2)'], resources=[], specialSquares=[]),
	'1,-1': Square(x=1, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, -2)', '(2, -1)', '(1, 0)', '(0, -1)'], resources=[], specialSquares=[]),
	'1,0': Square(x=1, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, -1)', '(2, 0)', '(1, 1)', '(0, 0)'], resources=[], specialSquares=[]),
	'1,1': Square(x=1, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, 0)', '(2, 1)', '(1, 2)', '(0, 1)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'1,2': Square(x=1, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, 1)', '(2, 2)', '(1, 3)', '(0, 2)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'1,3': Square(x=1, y=3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(1, 2)', '(2, 3)', '(1, 4)', '(0, 3)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'6,-2': Square(x=6, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(6, -3)', '(7, -2)', '(6, -1)', '(5, -2)'], resources=[], specialSquares=[]),
	'-7,-11': Square(x=-7, y=-11, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-7, -12)', '(-6, -11)', '(-7, -10)', '(-8, -11)'], resources=[], specialSquares=[]),
	'-7,-10': Square(x=-7, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-7, -11)', '(-6, -10)', '(-7, -9)', '(-8, -10)'], resources=[], specialSquares=[]),
	'-7,-2': Square(x=-7, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-7, -3)', '(-6, -2)', '(-7, -1)', '(-8, -2)'], resources=[], specialSquares=[]),
	'-7,-1': Square(x=-7, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-7, -2)', '(-6, -1)', '(-7, 0)', '(-8, -1)'], resources=[], specialSquares=[]),
	'-5,-9': Square(x=-5, y=-9, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-5, -10)', '(-4, -9)', '(-5, -8)', '(-6, -9)'], resources=[], specialSquares=[]),
	'5,-1': Square(x=5, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(5, -2)', '(6, -1)', '(5, 0)', '(4, -1)'], resources=[], specialSquares=[]),
	'5,2': Square(x=5, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(5, 1)', '(6, 2)', '(5, 3)', '(4, 2)'], resources=[], specialSquares=[]),
	'4,0': Square(x=4, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(4, -1)', '(5, 0)', '(4, 1)', '(3, 0)'], resources=[], specialSquares=[]),
	'4,1': Square(x=4, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(4, 0)', '(5, 1)', '(4, 2)', '(3, 1)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'4,2': Square(x=4, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(4, 1)', '(5, 2)', '(4, 3)', '(3, 2)'], resources=[], specialSquares=[]),
	'7,-3': Square(x=7, y=-3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(7, -4)', '(8, -3)', '(7, -2)', '(6, -3)'], resources=[], specialSquares=[]),
	'-8,-10': Square(x=-8, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-8, -11)', '(-7, -10)', '(-8, -9)', '(-9, -10)'], resources=[], specialSquares=[]),
	'2,-8': Square(x=2, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(2, -9)', '(3, -8)', '(2, -7)', '(1, -8)'], resources=[], specialSquares=[]),
	'2,-2': Square(x=2, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(2, -3)', '(3, -2)', '(2, -1)', '(1, -2)'], resources=[], specialSquares=[]),
	'2,0': Square(x=2, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(2, -1)', '(3, 0)', '(2, 1)', '(1, 0)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'2,1': Square(x=2, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(2, 0)', '(3, 1)', '(2, 2)', '(1, 1)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'2,2': Square(x=2, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(2, 1)', '(3, 2)', '(2, 3)', '(1, 2)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'2,3': Square(x=2, y=3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(2, 2)', '(3, 3)', '(2, 4)', '(1, 3)'], resources=[], specialSquares=[]),
	'-2,-7': Square(x=-2, y=-7, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-2, -8)', '(-1, -7)', '(-2, -6)', '(-3, -7)'], resources=[], specialSquares=[]),
	'-2,-6': Square(x=-2, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-2, -7)', '(-1, -6)', '(-2, -5)', '(-3, -6)'], resources=[], specialSquares=[]),
	'-2,-5': Square(x=-2, y=-5, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-2, -6)', '(-1, -5)', '(-2, -4)', '(-3, -5)'], resources=[], specialSquares=[]),
	'-1,-8': Square(x=-1, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-1, -9)', '(0, -8)', '(-1, -7)', '(-2, -8)'], resources=[], specialSquares=[]),
	'-1,-7': Square(x=-1, y=-7, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-1, -8)', '(0, -7)', '(-1, -6)', '(-2, -7)'], resources=[], specialSquares=[]),
	'-1,-6': Square(x=-1, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-1, -7)', '(0, -6)', '(-1, -5)', '(-2, -6)'], resources=[], specialSquares=[]),
	'-1,-4': Square(x=-1, y=-4, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-1, -5)', '(0, -4)', '(-1, -3)', '(-2, -4)'], resources=[], specialSquares=[]),
	'-11,-22': Square(x=-11, y=-22, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-11, -23)', '(-10, -22)', '(-11, -21)', '(-12, -22)'], resources=[], specialSquares=[]),
	'-11,-21': Square(x=-11, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-11, -22)', '(-10, -21)', '(-11, -20)', '(-12, -21)'], resources=[], specialSquares=[]),
	'-11,-20': Square(x=-11, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-11, -21)', '(-10, -20)', '(-11, -19)', '(-12, -20)'], resources=[], specialSquares=[]),
	'-11,-19': Square(x=-11, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-11, -20)', '(-10, -19)', '(-11, -18)', '(-12, -19)'], resources=[], specialSquares=[]),
	'-11,-18': Square(x=-11, y=-18, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-11, -19)', '(-10, -18)', '(-11, -17)', '(-12, -18)'], resources=[], specialSquares=[]),
	'0,-7': Square(x=0, y=-7, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(0, -8)', '(1, -7)', '(0, -6)', '(-1, -7)'], resources=[], specialSquares=[]),
	'0,-6': Square(x=0, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(0, -7)', '(1, -6)', '(0, -5)', '(-1, -6)'], resources=[], specialSquares=[]),
	'0,-4': Square(x=0, y=-4, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(0, -5)', '(1, -4)', '(0, -3)', '(-1, -4)'], resources=[], specialSquares=[]),
	'0,-3': Square(x=0, y=-3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(0, -4)', '(1, -3)', '(0, -2)', '(-1, -3)'], resources=[], specialSquares=[]),
	'0,0': Square(x=0, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(0, -1)', '(1, 0)', '(0, 1)', '(-1, 0)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'0,1': Square(x=0, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(0, 0)', '(1, 1)', '(0, 2)', '(-1, 1)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,0': Square(x=3, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(3, -1)', '(4, 0)', '(3, 1)', '(2, 0)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,1': Square(x=3, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(3, 0)', '(4, 1)', '(3, 2)', '(2, 1)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,2': Square(x=3, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(3, 1)', '(4, 2)', '(3, 3)', '(2, 2)'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,3': Square(x=3, y=3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(3, 2)', '(4, 3)', '(3, 4)', '(2, 3)'], resources=[], specialSquares=[]),
	'-6,-10': Square(x=-6, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-6, -11)', '(-5, -10)', '(-6, -9)', '(-7, -10)'], resources=[], specialSquares=[]),
	'-6,-9': Square(x=-6, y=-9, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-6, -10)', '(-5, -9)', '(-6, -8)', '(-7, -9)'], resources=[], specialSquares=[]),
	'-6,-1': Square(x=-6, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-6, -2)', '(-5, -1)', '(-6, 0)', '(-7, -1)'], resources=[], specialSquares=[]),
	'-12,-21': Square(x=-12, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-12, -22)', '(-11, -21)', '(-12, -20)', '(-13, -21)'], resources=[], specialSquares=[]),
	'-12,-20': Square(x=-12, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-12, -21)', '(-11, -20)', '(-12, -19)', '(-13, -20)'], resources=[], specialSquares=[]),
	'-12,-19': Square(x=-12, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-12, -20)', '(-11, -19)', '(-12, -18)', '(-13, -19)'], resources=[], specialSquares=[]),
	'-12,-18': Square(x=-12, y=-18, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['(-12, -19)', '(-11, -18)', '(-12, -17)', '(-13, -18)'], resources=[], specialSquares=[]),
}