from src.utils.DofusMapEnum import DofusMap
from src.utils.Square import Square
from src.utils.RESOURCES import CEREAL
from src.utils.RESOURCES import FISH
from src.utils.RESOURCES import FLOWER
from src.utils.RESOURCES import RESOURCES
from src.utils.RESOURCES import ORE
from src.utils.RESOURCES import WOOD

Incarnam = {
	'4,-4': Square(x=4, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(4, -5)', '(5, -4)', '(4, -3)', '(3, -4)'], resources=[(RESOURCES[CEREAL.BLE], 1)], specialSquares=[]),
	'4,-3': Square(x=4, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(4, -4)', '(5, -3)', '(4, -2)', '(3, -3)'], resources=[], specialSquares=[]),
	'4,-1': Square(x=4, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(4, -2)', '(5, -1)', '(4, 0)', '(3, -1)'], resources=[], specialSquares=[]),
	'4,0': Square(x=4, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(4, -1)', '(5, 0)', '(4, 1)', '(3, 0)'], resources=[], specialSquares=[]),
	'4,1': Square(x=4, y=1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(4, 0)', '(5, 1)', '(4, 2)', '(3, 1)'], resources=[], specialSquares=[]),
	'-3,-6': Square(x=-3, y=-6, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-3, -7)', '(-2, -6)', '(-3, -5)', '(-4, -6)'], resources=[(RESOURCES[CEREAL.BLE], 1)], specialSquares=[]),
	'-3,-5': Square(x=-3, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-3, -6)', '(-2, -5)', '(-3, -4)', '(-4, -5)'], resources=[(RESOURCES[CEREAL.BLE], 6)], specialSquares=[]),
	'2,-5': Square(x=2, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, -6)', '(3, -5)', '(2, -4)', '(1, -5)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'2,-4': Square(x=2, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, -5)', '(3, -4)', '(2, -3)', '(1, -4)'], resources=[(RESOURCES[FLOWER.ORTIE], 1), (RESOURCES[ORE.FER], 15)], specialSquares=[]),
	'2,-3': Square(x=2, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, -4)', '(3, -3)', '(2, -2)', '(1, -3)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'2,-2': Square(x=2, y=-2, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, -3)', '(3, -2)', '(2, -1)', '(1, -2)'], resources=[(RESOURCES[FLOWER.ORTIE], 3), (RESOURCES[WOOD.FRENE], 4)], specialSquares=[]),
	'2,-1': Square(x=2, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, -2)', '(3, -1)', '(2, 0)', '(1, -1)'], resources=[(RESOURCES[FLOWER.ORTIE], 2), (RESOURCES[WOOD.FRENE], 6)], specialSquares=[]),
	'2,0': Square(x=2, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, -1)', '(3, 0)', '(2, 1)', '(1, 0)'], resources=[(RESOURCES[FLOWER.ORTIE], 2), (RESOURCES[WOOD.FRENE], 1)], specialSquares=[]),
	'2,6': Square(x=2, y=6, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, 5)', '(3, 6)', '(2, 7)', '(1, 6)'], resources=[], specialSquares=[]),
	'2,8': Square(x=2, y=8, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(2, 7)', '(3, 8)', '(2, 9)', '(1, 8)'], resources=[], specialSquares=[]),
	'-1,-6': Square(x=-1, y=-6, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -7)', '(0, -6)', '(-1, -5)', '(-2, -6)'], resources=[(RESOURCES[CEREAL.BLE], 8)], specialSquares=[]),
	'-1,-5': Square(x=-1, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -6)', '(0, -5)', '(-1, -4)', '(-2, -5)'], resources=[(RESOURCES[CEREAL.BLE], 12)], specialSquares=[]),
	'-1,-4': Square(x=-1, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -5)', '(0, -4)', '(-1, -3)', '(-2, -4)'], resources=[(RESOURCES[CEREAL.BLE], 11)], specialSquares=[]),
	'-1,-3': Square(x=-1, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -4)', '(0, -3)', '(-1, -2)', '(-2, -3)'], resources=[(RESOURCES[CEREAL.BLE], 5)], specialSquares=[]),
	'-1,-2': Square(x=-1, y=-2, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -3)', '(0, -2)', '(-1, -1)', '(-2, -2)'], resources=[(RESOURCES[FISH.GOUJON], 7), (RESOURCES[FLOWER.ORTIE], 2)], specialSquares=[]),
	'-1,-1': Square(x=-1, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -2)', '(0, -1)', '(-1, 0)', '(-2, -1)'], resources=[(RESOURCES[FISH.GOUJON], 11)], specialSquares=[]),
	'-1,0': Square(x=-1, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, -1)', '(0, 0)', '(-1, 1)', '(-2, 0)'], resources=[(RESOURCES[FISH.GOUJON], 7), (RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'-1,1': Square(x=-1, y=1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-1, 0)', '(0, 1)', '(-1, 2)', '(-2, 1)'], resources=[], specialSquares=[]),
	'-2,-6': Square(x=-2, y=-6, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -7)', '(-1, -6)', '(-2, -5)', '(-3, -6)'], resources=[(RESOURCES[CEREAL.BLE], 9)], specialSquares=[]),
	'-2,-5': Square(x=-2, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -6)', '(-1, -5)', '(-2, -4)', '(-3, -5)'], resources=[(RESOURCES[CEREAL.BLE], 12)], specialSquares=[]),
	'-2,-4': Square(x=-2, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -5)', '(-1, -4)', '(-2, -3)', '(-3, -4)'], resources=[(RESOURCES[CEREAL.BLE], 8)], specialSquares=[]),
	'-2,-3': Square(x=-2, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -4)', '(-1, -3)', '(-2, -2)', '(-3, -3)'], resources=[(RESOURCES[CEREAL.BLE], 1)], specialSquares=[]),
	'-2,-2': Square(x=-2, y=-2, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -3)', '(-1, -2)', '(-2, -1)', '(-3, -2)'], resources=[(RESOURCES[FISH.GOUJON], 4)], specialSquares=[]),
	'-2,-1': Square(x=-2, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -2)', '(-1, -1)', '(-2, 0)', '(-3, -1)'], resources=[(RESOURCES[FISH.GOUJON], 6), (RESOURCES[FLOWER.ORTIE], 2)], specialSquares=[]),
	'-2,0': Square(x=-2, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(-2, -1)', '(-1, 0)', '(-2, 1)', '(-3, 0)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'0,-5': Square(x=0, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, -6)', '(1, -5)', '(0, -4)', '(-1, -5)'], resources=[(RESOURCES[CEREAL.BLE], 5), (RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'0,-4': Square(x=0, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, -5)', '(1, -4)', '(0, -3)', '(-1, -4)'], resources=[(RESOURCES[CEREAL.BLE], 2)], specialSquares=[]),
	'0,-3': Square(x=0, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, -4)', '(1, -3)', '(0, -2)', '(-1, -3)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'0,-2': Square(x=0, y=-2, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, -3)', '(1, -2)', '(0, -1)', '(-1, -2)'], resources=[(RESOURCES[FISH.GOUJON], 3), (RESOURCES[FLOWER.ORTIE], 2)], specialSquares=[]),
	'0,-1': Square(x=0, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, -2)', '(1, -1)', '(0, 0)', '(-1, -1)'], resources=[(RESOURCES[FISH.GOUJON], 9)], specialSquares=[]),
	'0,0': Square(x=0, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, -1)', '(1, 0)', '(0, 1)', '(-1, 0)'], resources=[(RESOURCES[FISH.GOUJON], 5)], specialSquares=[]),
	'0,1': Square(x=0, y=1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(0, 0)', '(1, 1)', '(0, 2)', '(-1, 1)'], resources=[], specialSquares=[]),
	'3,-5': Square(x=3, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, -6)', '(4, -5)', '(3, -4)', '(2, -5)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'3,-4': Square(x=3, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, -5)', '(4, -4)', '(3, -3)', '(2, -4)'], resources=[(RESOURCES[FLOWER.ORTIE], 2), (RESOURCES[ORE.FER], 15)], specialSquares=[]),
	'3,-3': Square(x=3, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, -4)', '(4, -3)', '(3, -2)', '(2, -3)'], resources=[(RESOURCES[FLOWER.ORTIE], 2)], specialSquares=[]),
	'3,-2': Square(x=3, y=-2, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, -3)', '(4, -2)', '(3, -1)', '(2, -2)'], resources=[(RESOURCES[FLOWER.ORTIE], 3), (RESOURCES[WOOD.FRENE], 2)], specialSquares=[]),
	'3,-1': Square(x=3, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, -2)', '(4, -1)', '(3, 0)', '(2, -1)'], resources=[(RESOURCES[FLOWER.ORTIE], 1), (RESOURCES[WOOD.FRENE], 2)], specialSquares=[]),
	'3,0': Square(x=3, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, -1)', '(4, 0)', '(3, 1)', '(2, 0)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'3,1': Square(x=3, y=1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, 0)', '(4, 1)', '(3, 2)', '(2, 1)'], resources=[], specialSquares=[]),
	'3,7': Square(x=3, y=7, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(3, 6)', '(4, 7)', '(3, 8)', '(2, 7)'], resources=[], specialSquares=[]),
	'1,-5': Square(x=1, y=-5, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, -6)', '(2, -5)', '(1, -4)', '(0, -5)'], resources=[(RESOURCES[CEREAL.BLE], 1)], specialSquares=[]),
	'1,-4': Square(x=1, y=-4, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, -5)', '(2, -4)', '(1, -3)', '(0, -4)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'1,-3': Square(x=1, y=-3, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, -4)', '(2, -3)', '(1, -2)', '(0, -3)'], resources=[(RESOURCES[FLOWER.ORTIE], 1)], specialSquares=[]),
	'1,-2': Square(x=1, y=-2, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, -3)', '(2, -2)', '(1, -1)', '(0, -2)'], resources=[(RESOURCES[FLOWER.ORTIE], 3), (RESOURCES[WOOD.FRENE], 3)], specialSquares=[]),
	'1,-1': Square(x=1, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, -2)', '(2, -1)', '(1, 0)', '(0, -1)'], resources=[(RESOURCES[FLOWER.ORTIE], 2), (RESOURCES[WOOD.FRENE], 5)], specialSquares=[]),
	'1,0': Square(x=1, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, -1)', '(2, 0)', '(1, 1)', '(0, 0)'], resources=[(RESOURCES[FLOWER.ORTIE], 2), (RESOURCES[WOOD.FRENE], 3)], specialSquares=[]),
	'1,7': Square(x=1, y=7, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(1, 6)', '(2, 7)', '(1, 8)', '(0, 7)'], resources=[], specialSquares=[]),
	'5,-1': Square(x=5, y=-1, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(5, -2)', '(6, -1)', '(5, 0)', '(4, -1)'], resources=[], specialSquares=[]),
	'5,0': Square(x=5, y=0, dofusMap=DofusMap.INCARNAM, city="Astrub", place="", adjs=['(5, -1)', '(6, 0)', '(5, 1)', '(4, 0)'], resources=[], specialSquares=[]),
}