from src.utils.DofusMapEnum import DofusMap
from src.utils.Square import Square
from src.utils.RESOURCES import CEREAL
from src.utils.RESOURCES import FISH
from src.utils.RESOURCES import FLOWER
from src.utils.RESOURCES import RESOURCES
from src.utils.RESOURCES import ORE
from src.utils.RESOURCES import WOOD

Srambad = {
	'9,3': Square(x=9, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(9, 2)', '(10, 3)', '(9, 4)', '(8, 3)'], resources=[], specialSquares=[]),
	'9,6': Square(x=9, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(9, 5)', '(10, 6)', '(9, 7)', '(8, 6)'], resources=[], specialSquares=[]),
	'4,0': Square(x=4, y=0, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(4, -1)', '(5, 0)', '(4, 1)', '(3, 0)'], resources=[], specialSquares=[]),
	'4,1': Square(x=4, y=1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(4, 0)', '(5, 1)', '(4, 2)', '(3, 1)'], resources=[], specialSquares=[]),
	'4,2': Square(x=4, y=2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(4, 1)', '(5, 2)', '(4, 3)', '(3, 2)'], resources=[], specialSquares=[]),
	'4,3': Square(x=4, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(4, 2)', '(5, 3)', '(4, 4)', '(3, 3)'], resources=[], specialSquares=[]),
	'4,8': Square(x=4, y=8, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(4, 7)', '(5, 8)', '(4, 9)', '(3, 8)'], resources=[], specialSquares=[]),
	'4,9': Square(x=4, y=9, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(4, 8)', '(5, 9)', '(4, 10)', '(3, 9)'], resources=[], specialSquares=[]),
	'-2,4': Square(x=-2, y=4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(-2, 3)', '(-1, 4)', '(-2, 5)', '(-3, 4)'], resources=[], specialSquares=[]),
	'-2,5': Square(x=-2, y=5, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(-2, 4)', '(-1, 5)', '(-2, 6)', '(-3, 5)'], resources=[], specialSquares=[]),
	'-2,6': Square(x=-2, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(-2, 5)', '(-1, 6)', '(-2, 7)', '(-3, 6)'], resources=[], specialSquares=[]),
	'6,-2': Square(x=6, y=-2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, -3)', '(7, -2)', '(6, -1)', '(5, -2)'], resources=[], specialSquares=[]),
	'6,-1': Square(x=6, y=-1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, -2)', '(7, -1)', '(6, 0)', '(5, -1)'], resources=[], specialSquares=[]),
	'6,0': Square(x=6, y=0, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, -1)', '(7, 0)', '(6, 1)', '(5, 0)'], resources=[], specialSquares=[]),
	'6,1': Square(x=6, y=1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 0)', '(7, 1)', '(6, 2)', '(5, 1)'], resources=[], specialSquares=[]),
	'6,2': Square(x=6, y=2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 1)', '(7, 2)', '(6, 3)', '(5, 2)'], resources=[], specialSquares=[]),
	'6,3': Square(x=6, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 2)', '(7, 3)', '(6, 4)', '(5, 3)'], resources=[], specialSquares=[]),
	'6,5': Square(x=6, y=5, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 4)', '(7, 5)', '(6, 6)', '(5, 5)'], resources=[], specialSquares=[]),
	'6,6': Square(x=6, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 5)', '(7, 6)', '(6, 7)', '(5, 6)'], resources=[], specialSquares=[]),
	'6,7': Square(x=6, y=7, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 6)', '(7, 7)', '(6, 8)', '(5, 7)'], resources=[], specialSquares=[]),
	'6,8': Square(x=6, y=8, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 7)', '(7, 8)', '(6, 9)', '(5, 8)'], resources=[], specialSquares=[]),
	'6,9': Square(x=6, y=9, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(6, 8)', '(7, 9)', '(6, 10)', '(5, 9)'], resources=[], specialSquares=[]),
	'5,-2': Square(x=5, y=-2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, -3)', '(6, -2)', '(5, -1)', '(4, -2)'], resources=[], specialSquares=[]),
	'5,-1': Square(x=5, y=-1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, -2)', '(6, -1)', '(5, 0)', '(4, -1)'], resources=[], specialSquares=[]),
	'5,0': Square(x=5, y=0, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, -1)', '(6, 0)', '(5, 1)', '(4, 0)'], resources=[], specialSquares=[]),
	'5,1': Square(x=5, y=1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, 0)', '(6, 1)', '(5, 2)', '(4, 1)'], resources=[], specialSquares=[]),
	'5,2': Square(x=5, y=2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, 1)', '(6, 2)', '(5, 3)', '(4, 2)'], resources=[], specialSquares=[]),
	'5,3': Square(x=5, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, 2)', '(6, 3)', '(5, 4)', '(4, 3)'], resources=[], specialSquares=[]),
	'5,7': Square(x=5, y=7, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, 6)', '(6, 7)', '(5, 8)', '(4, 7)'], resources=[], specialSquares=[]),
	'5,8': Square(x=5, y=8, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, 7)', '(6, 8)', '(5, 9)', '(4, 8)'], resources=[], specialSquares=[]),
	'5,9': Square(x=5, y=9, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(5, 8)', '(6, 9)', '(5, 10)', '(4, 9)'], resources=[], specialSquares=[]),
	'7,-3': Square(x=7, y=-3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, -4)', '(8, -3)', '(7, -2)', '(6, -3)'], resources=[], specialSquares=[]),
	'7,-2': Square(x=7, y=-2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, -3)', '(8, -2)', '(7, -1)', '(6, -2)'], resources=[], specialSquares=[]),
	'7,-1': Square(x=7, y=-1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, -2)', '(8, -1)', '(7, 0)', '(6, -1)'], resources=[], specialSquares=[]),
	'7,0': Square(x=7, y=0, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, -1)', '(8, 0)', '(7, 1)', '(6, 0)'], resources=[], specialSquares=[]),
	'7,2': Square(x=7, y=2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, 1)', '(8, 2)', '(7, 3)', '(6, 2)'], resources=[], specialSquares=[]),
	'7,3': Square(x=7, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, 2)', '(8, 3)', '(7, 4)', '(6, 3)'], resources=[], specialSquares=[]),
	'7,4': Square(x=7, y=4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, 3)', '(8, 4)', '(7, 5)', '(6, 4)'], resources=[], specialSquares=[]),
	'7,7': Square(x=7, y=7, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, 6)', '(8, 7)', '(7, 8)', '(6, 7)'], resources=[], specialSquares=[]),
	'7,8': Square(x=7, y=8, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, 7)', '(8, 8)', '(7, 9)', '(6, 8)'], resources=[], specialSquares=[]),
	'7,9': Square(x=7, y=9, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(7, 8)', '(8, 9)', '(7, 10)', '(6, 9)'], resources=[], specialSquares=[]),
	'2,2': Square(x=2, y=2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(2, 1)', '(3, 2)', '(2, 3)', '(1, 2)'], resources=[], specialSquares=[]),
	'2,6': Square(x=2, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(2, 5)', '(3, 6)', '(2, 7)', '(1, 6)'], resources=[], specialSquares=[]),
	'-1,4': Square(x=-1, y=4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(-1, 3)', '(0, 4)', '(-1, 5)', '(-2, 4)'], resources=[], specialSquares=[]),
	'-1,5': Square(x=-1, y=5, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(-1, 4)', '(0, 5)', '(-1, 6)', '(-2, 5)'], resources=[], specialSquares=[]),
	'-1,6': Square(x=-1, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(-1, 5)', '(0, 6)', '(-1, 7)', '(-2, 6)'], resources=[], specialSquares=[]),
	'8,-4': Square(x=8, y=-4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, -5)', '(9, -4)', '(8, -3)', '(7, -4)'], resources=[], specialSquares=[]),
	'8,-2': Square(x=8, y=-2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, -3)', '(9, -2)', '(8, -1)', '(7, -2)'], resources=[], specialSquares=[]),
	'8,-1': Square(x=8, y=-1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, -2)', '(9, -1)', '(8, 0)', '(7, -1)'], resources=[], specialSquares=[]),
	'8,3': Square(x=8, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, 2)', '(9, 3)', '(8, 4)', '(7, 3)'], resources=[], specialSquares=[]),
	'8,4': Square(x=8, y=4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, 3)', '(9, 4)', '(8, 5)', '(7, 4)'], resources=[], specialSquares=[]),
	'8,5': Square(x=8, y=5, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, 4)', '(9, 5)', '(8, 6)', '(7, 5)'], resources=[], specialSquares=[]),
	'8,6': Square(x=8, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, 5)', '(9, 6)', '(8, 7)', '(7, 6)'], resources=[], specialSquares=[]),
	'8,7': Square(x=8, y=7, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, 6)', '(9, 7)', '(8, 8)', '(7, 7)'], resources=[], specialSquares=[]),
	'8,8': Square(x=8, y=8, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(8, 7)', '(9, 8)', '(8, 9)', '(7, 8)'], resources=[], specialSquares=[]),
	'0,0': Square(x=0, y=0, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(0, -1)', '(1, 0)', '(0, 1)', '(-1, 0)'], resources=[], specialSquares=[]),
	'0,4': Square(x=0, y=4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(0, 3)', '(1, 4)', '(0, 5)', '(-1, 4)'], resources=[], specialSquares=[]),
	'0,5': Square(x=0, y=5, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(0, 4)', '(1, 5)', '(0, 6)', '(-1, 5)'], resources=[], specialSquares=[]),
	'0,6': Square(x=0, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(0, 5)', '(1, 6)', '(0, 7)', '(-1, 6)'], resources=[], specialSquares=[]),
	'0,7': Square(x=0, y=7, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(0, 6)', '(1, 7)', '(0, 8)', '(-1, 7)'], resources=[], specialSquares=[]),
	'3,2': Square(x=3, y=2, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(3, 1)', '(4, 2)', '(3, 3)', '(2, 2)'], resources=[], specialSquares=[]),
	'3,3': Square(x=3, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(3, 2)', '(4, 3)', '(3, 4)', '(2, 3)'], resources=[], specialSquares=[]),
	'3,7': Square(x=3, y=7, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(3, 6)', '(4, 7)', '(3, 8)', '(2, 7)'], resources=[], specialSquares=[]),
	'1,1': Square(x=1, y=1, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(1, 0)', '(2, 1)', '(1, 2)', '(0, 1)'], resources=[], specialSquares=[]),
	'1,5': Square(x=1, y=5, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(1, 4)', '(2, 5)', '(1, 6)', '(0, 5)'], resources=[], specialSquares=[]),
	'1,6': Square(x=1, y=6, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(1, 5)', '(2, 6)', '(1, 7)', '(0, 6)'], resources=[], specialSquares=[]),
	'10,3': Square(x=10, y=3, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(10, 2)', '(11, 3)', '(10, 4)', '(9, 3)'], resources=[], specialSquares=[]),
	'10,4': Square(x=10, y=4, dofusMap=DofusMap.SRAMBAD, city="Astrub", place="", adjs=['(10, 3)', '(11, 4)', '(10, 5)', '(9, 4)'], resources=[], specialSquares=[]),
}