from src.utils.DofusMapEnum import DofusMap
from src.utils.Square import Square
from src.utils.RESOURCES import FLOWER
from src.utils.RESOURCES import RESOURCES

Ecaflipus = {
	'-9,-22': Square(x=-9, y=-22, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '-9,-21', '-10,-22'], resources=[], specialSquares=[]),
	'-9,-21': Square(x=-9, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-9,-22', None, '-9,-20', '-10,-21'], resources=[], specialSquares=[]),
	'-9,-20': Square(x=-9, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-9,-21', None, '-9,-19', '-10,-20'], resources=[], specialSquares=[]),
	'-9,-19': Square(x=-9, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-9,-20', None, None, '-10,-19'], resources=[], specialSquares=[]),
	'-9,-10': Square(x=-9, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-8,-10', None, None], resources=[], specialSquares=[]),
	'-9,-2': Square(x=-9, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'-13,-21': Square(x=-13, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-12,-21', None, None], resources=[], specialSquares=[]),
	'-13,-19': Square(x=-13, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-12,-19', '-13,-18', None], resources=[], specialSquares=[]),
	'-13,-18': Square(x=-13, y=-18, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-13,-19', '-12,-18', None, None], resources=[], specialSquares=[]),
	'-10,-22': Square(x=-10, y=-22, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-9,-22', '-10,-21', '-11,-22'], resources=[], specialSquares=[]),
	'-10,-21': Square(x=-10, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-10,-22', '-9,-21', '-10,-20', '-11,-21'], resources=[], specialSquares=[]),
	'-10,-20': Square(x=-10, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-10,-21', '-9,-20', '-10,-19', '-11,-20'], resources=[], specialSquares=[]),
	'-10,-19': Square(x=-10, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-10,-20', '-9,-19', None, '-11,-19'], resources=[], specialSquares=[]),
	'-10,-11': Square(x=-10, y=-11, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'-3,-8': Square(x=-3, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, '-4,-8'], resources=[], specialSquares=[]),
	'-3,-6': Square(x=-3, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-2,-6', None, None], resources=[], specialSquares=[]),
	'-4,-8': Square(x=-4, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-3,-8', None, None], resources=[], specialSquares=[]),
	'1,-8': Square(x=1, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '2,-8', None, None], resources=[], specialSquares=[]),
	'1,-5': Square(x=1, y=-5, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'1,-3': Square(x=1, y=-3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '1,-2', '0,-3'], resources=[], specialSquares=[]),
	'1,-2': Square(x=1, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['1,-3', '2,-2', '1,-1', None], resources=[], specialSquares=[]),
	'1,-1': Square(x=1, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['1,-2', None, '1,0', None], resources=[], specialSquares=[]),
	'1,0': Square(x=1, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['1,-1', '2,0', '1,1', '0,0'], resources=[], specialSquares=[]),
	'1,1': Square(x=1, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['1,0', '2,1', '1,2', '0,1'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'1,2': Square(x=1, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['1,1', '2,2', '1,3', None], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'1,3': Square(x=1, y=3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['1,2', '2,3', None, None], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'6,-2': Square(x=6, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'-7,-11': Square(x=-7, y=-11, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '-7,-10', None], resources=[], specialSquares=[]),
	'-7,-10': Square(x=-7, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-7,-11', '-6,-10', None, '-8,-10'], resources=[], specialSquares=[]),
	'-7,-2': Square(x=-7, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '-7,-1', None], resources=[], specialSquares=[]),
	'-7,-1': Square(x=-7, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-7,-2', '-6,-1', None, None], resources=[], specialSquares=[]),
	'-5,-9': Square(x=-5, y=-9, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, '-6,-9'], resources=[], specialSquares=[]),
	'5,-1': Square(x=5, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'5,2': Square(x=5, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, '4,2'], resources=[], specialSquares=[]),
	'4,0': Square(x=4, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '4,1', '3,0'], resources=[], specialSquares=[]),
	'4,1': Square(x=4, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['4,0', None, '4,2', '3,1'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'4,2': Square(x=4, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['4,1', '5,2', None, '3,2'], resources=[], specialSquares=[]),
	'7,-3': Square(x=7, y=-3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'-8,-10': Square(x=-8, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-7,-10', None, '-9,-10'], resources=[], specialSquares=[]),
	'2,-8': Square(x=2, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, '1,-8'], resources=[], specialSquares=[]),
	'2,-2': Square(x=2, y=-2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, '1,-2'], resources=[], specialSquares=[]),
	'2,0': Square(x=2, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '3,0', '2,1', '1,0'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'2,1': Square(x=2, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['2,0', '3,1', '2,2', '1,1'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'2,2': Square(x=2, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['2,1', '3,2', '2,3', '1,2'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'2,3': Square(x=2, y=3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['2,2', '3,3', None, '1,3'], resources=[], specialSquares=[]),
	'-2,-7': Square(x=-2, y=-7, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-1,-7', '-2,-6', None], resources=[], specialSquares=[]),
	'-2,-6': Square(x=-2, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-2,-7', '-1,-6', '-2,-5', '-3,-6'], resources=[], specialSquares=[]),
	'-2,-5': Square(x=-2, y=-5, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-2,-6', None, None, None], resources=[], specialSquares=[]),
	'-1,-8': Square(x=-1, y=-8, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '-1,-7', None], resources=[], specialSquares=[]),
	'-1,-7': Square(x=-1, y=-7, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-1,-8', '0,-7', '-1,-6', '-2,-7'], resources=[], specialSquares=[]),
	'-1,-6': Square(x=-1, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-1,-7', '0,-6', None, '-2,-6'], resources=[], specialSquares=[]),
	'-1,-4': Square(x=-1, y=-4, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '0,-4', None, None], resources=[], specialSquares=[]),
	'-11,-22': Square(x=-11, y=-22, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-10,-22', '-11,-21', None], resources=[], specialSquares=[]),
	'-11,-21': Square(x=-11, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-11,-22', '-10,-21', '-11,-20', '-12,-21'], resources=[], specialSquares=[]),
	'-11,-20': Square(x=-11, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-11,-21', '-10,-20', '-11,-19', '-12,-20'], resources=[], specialSquares=[]),
	'-11,-19': Square(x=-11, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-11,-20', '-10,-19', '-11,-18', '-12,-19'], resources=[], specialSquares=[]),
	'-11,-18': Square(x=-11, y=-18, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-11,-19', None, None, '-12,-18'], resources=[], specialSquares=[]),
	'0,-7': Square(x=0, y=-7, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '0,-6', '-1,-7'], resources=[], specialSquares=[]),
	'0,-6': Square(x=0, y=-6, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['0,-7', None, None, '-1,-6'], resources=[], specialSquares=[]),
	'0,-4': Square(x=0, y=-4, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '0,-3', '-1,-4'], resources=[], specialSquares=[]),
	'0,-3': Square(x=0, y=-3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['0,-4', '1,-3', None, None], resources=[], specialSquares=[]),
	'0,0': Square(x=0, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '1,0', '0,1', None], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'0,1': Square(x=0, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['0,0', '1,1', None, None], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,0': Square(x=3, y=0, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '4,0', '3,1', '2,0'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,1': Square(x=3, y=1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['3,0', '4,1', '3,2', '2,1'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,2': Square(x=3, y=2, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['3,1', '4,2', '3,3', '2,2'], resources=[(RESOURCES[FLOWER.TREFLE], 1)], specialSquares=[]),
	'3,3': Square(x=3, y=3, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['3,2', None, None, '2,3'], resources=[], specialSquares=[]),
	'-6,-10': Square(x=-6, y=-10, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, '-6,-9', '-7,-10'], resources=[], specialSquares=[]),
	'-6,-9': Square(x=-6, y=-9, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-6,-10', '-5,-9', None, None], resources=[], specialSquares=[]),
	'-6,-1': Square(x=-6, y=-1, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, None, None, '-7,-1'], resources=[], specialSquares=[]),
	'-12,-21': Square(x=-12, y=-21, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=[None, '-11,-21', '-12,-20', '-13,-21'], resources=[], specialSquares=[]),
	'-12,-20': Square(x=-12, y=-20, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-12,-21', '-11,-20', '-12,-19', None], resources=[], specialSquares=[]),
	'-12,-19': Square(x=-12, y=-19, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-12,-20', '-11,-19', '-12,-18', '-13,-19'], resources=[], specialSquares=[]),
	'-12,-18': Square(x=-12, y=-18, dofusMap=DofusMap.ECAFLIPUS, city="Astrub", place="", adjs=['-12,-19', '-11,-18', None, '-13,-18'], resources=[], specialSquares=[]),
}