from src.utils.DofusMapEnum import DofusMap
from src.utils.Square import Square
from src.utils.RESOURCES import CEREAL
from src.utils.RESOURCES import FISH
from src.utils.RESOURCES import FLOWER
from src.utils.RESOURCES import RESOURCES
from src.utils.RESOURCES import ORE
from src.utils.RESOURCES import WOOD

Enutrosor = {
	'-9,-6': Square(x=-9, y=-6, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-8,-6', '-9,-5', '-10,-6'], resources=[], specialSquares=[]),
	'-9,-5': Square(x=-9, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-9,-6', '-8,-5', '-9,-4', '-10,-5'], resources=[], specialSquares=[]),
	'-9,-4': Square(x=-9, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-9,-5', '-8,-4', None, '-10,-4'], resources=[], specialSquares=[]),
	'3,-5': Square(x=3, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, '3,-4', '2,-5'], resources=[], specialSquares=[]),
	'3,-4': Square(x=3, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['3,-5', None, '3,-3', '2,-4'], resources=[], specialSquares=[]),
	'3,-3': Square(x=3, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['3,-4', None, None, '2,-3'], resources=[], specialSquares=[]),
	'-10,-6': Square(x=-10, y=-6, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-9,-6', '-10,-5', None], resources=[], specialSquares=[]),
	'-10,-5': Square(x=-10, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-10,-6', '-9,-5', '-10,-4', None], resources=[], specialSquares=[]),
	'-10,-4': Square(x=-10, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-10,-5', '-9,-4', None, None], resources=[], specialSquares=[]),
	'-3,-10': Square(x=-3, y=-10, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, '-3,-9', '-4,-10'], resources=[], specialSquares=[]),
	'-3,-9': Square(x=-3, y=-9, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-3,-10', None, '-3,-8', '-4,-9'], resources=[], specialSquares=[]),
	'-3,-8': Square(x=-3, y=-8, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-3,-9', None, None, '-4,-8'], resources=[], specialSquares=[]),
	'-3,-4': Square(x=-3, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-2,-4', '-3,-3', '-4,-4'], resources=[], specialSquares=[]),
	'-3,-3': Square(x=-3, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-3,-4', '-2,-3', '-3,-2', '-4,-3'], resources=[], specialSquares=[]),
	'-3,-2': Square(x=-3, y=-2, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-3,-3', '-2,-2', '-3,-1', '-4,-2'], resources=[], specialSquares=[]),
	'-3,-1': Square(x=-3, y=-1, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-3,-2', '-2,-1', None, '-4,-1'], resources=[], specialSquares=[]),
	'-2,-4': Square(x=-2, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, '-2,-3', '-3,-4'], resources=[], specialSquares=[]),
	'-2,-3': Square(x=-2, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-2,-4', None, '-2,-2', '-3,-3'], resources=[], specialSquares=[]),
	'-2,-2': Square(x=-2, y=-2, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-2,-3', '-1,-2', '-2,-1', '-3,-2'], resources=[], specialSquares=[]),
	'-2,-1': Square(x=-2, y=-1, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-2,-2', '-1,-1', None, '-3,-1'], resources=[], specialSquares=[]),
	'1,-5': Square(x=1, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '2,-5', '1,-4', '0,-5'], resources=[], specialSquares=[]),
	'1,-4': Square(x=1, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['1,-5', '2,-4', '1,-3', '0,-4'], resources=[], specialSquares=[]),
	'1,-3': Square(x=1, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['1,-4', '2,-3', None, '0,-3'], resources=[], specialSquares=[]),
	'-7,-6': Square(x=-7, y=-6, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, '-7,-5', '-8,-6'], resources=[], specialSquares=[]),
	'-7,-5': Square(x=-7, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-7,-6', None, '-7,-4', '-8,-5'], resources=[], specialSquares=[]),
	'-7,-4': Square(x=-7, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-7,-5', None, None, '-8,-4'], resources=[], specialSquares=[]),
	'-5,-10': Square(x=-5, y=-10, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-4,-10', '-5,-9', None], resources=[], specialSquares=[]),
	'-5,-9': Square(x=-5, y=-9, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-5,-10', '-4,-9', '-5,-8', None], resources=[], specialSquares=[]),
	'-5,-8': Square(x=-5, y=-8, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-5,-9', '-4,-8', None, '-6,-8'], resources=[], specialSquares=[]),
	'-5,-5': Square(x=-5, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'-5,-3': Square(x=-5, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-4,-3', '-5,-2', '-6,-3'], resources=[], specialSquares=[]),
	'-5,-2': Square(x=-5, y=-2, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-5,-3', '-4,-2', '-5,-1', '-6,-2'], resources=[], specialSquares=[]),
	'-5,-1': Square(x=-5, y=-1, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-5,-2', '-4,-1', None, '-6,-1'], resources=[], specialSquares=[]),
	'-6,-8': Square(x=-6, y=-8, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-5,-8', None, None], resources=[], specialSquares=[]),
	'-6,-3': Square(x=-6, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-5,-3', '-6,-2', None], resources=[], specialSquares=[]),
	'-6,-2': Square(x=-6, y=-2, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-6,-3', '-5,-2', '-6,-1', None], resources=[], specialSquares=[]),
	'-6,-1': Square(x=-6, y=-1, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-6,-2', '-5,-1', None, None], resources=[], specialSquares=[]),
	'-4,-10': Square(x=-4, y=-10, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-3,-10', '-4,-9', '-5,-10'], resources=[], specialSquares=[]),
	'-4,-9': Square(x=-4, y=-9, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-4,-10', '-3,-9', '-4,-8', '-5,-9'], resources=[], specialSquares=[]),
	'-4,-8': Square(x=-4, y=-8, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-4,-9', '-3,-8', None, '-5,-8'], resources=[], specialSquares=[]),
	'-4,-4': Square(x=-4, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-3,-4', '-4,-3', None], resources=[], specialSquares=[]),
	'-4,-3': Square(x=-4, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-4,-4', '-3,-3', '-4,-2', '-5,-3'], resources=[], specialSquares=[]),
	'-4,-2': Square(x=-4, y=-2, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-4,-3', '-3,-2', '-4,-1', '-5,-2'], resources=[], specialSquares=[]),
	'-4,-1': Square(x=-4, y=-1, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-4,-2', '-3,-1', None, '-5,-1'], resources=[], specialSquares=[]),
	'-1,-2': Square(x=-1, y=-2, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, '-1,-1', '-2,-2'], resources=[], specialSquares=[]),
	'-1,-1': Square(x=-1, y=-1, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-1,-2', None, None, '-2,-1'], resources=[], specialSquares=[]),
	'-8,-6': Square(x=-8, y=-6, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '-7,-6', '-8,-5', '-9,-6'], resources=[], specialSquares=[]),
	'-8,-5': Square(x=-8, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-8,-6', '-7,-5', '-8,-4', '-9,-5'], resources=[], specialSquares=[]),
	'-8,-4': Square(x=-8, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['-8,-5', '-7,-4', None, '-9,-4'], resources=[], specialSquares=[]),
	'0,-5': Square(x=0, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '1,-5', '0,-4', None], resources=[], specialSquares=[]),
	'0,-4': Square(x=0, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['0,-5', '1,-4', '0,-3', None], resources=[], specialSquares=[]),
	'0,-3': Square(x=0, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['0,-4', '1,-3', None, None], resources=[], specialSquares=[]),
	'0,0': Square(x=0, y=0, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'2,-5': Square(x=2, y=-5, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=[None, '3,-5', '2,-4', '1,-5'], resources=[], specialSquares=[]),
	'2,-4': Square(x=2, y=-4, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['2,-5', '3,-4', '2,-3', '1,-4'], resources=[], specialSquares=[]),
	'2,-3': Square(x=2, y=-3, dofusMap=DofusMap.ENUTROSOR, city="Astrub", place="", adjs=['2,-4', '3,-3', None, '1,-3'], resources=[], specialSquares=[]),
}