from src.utils.DofusMapEnum import DofusMap
from src.utils.Square import Square
from src.utils.RESOURCES import CEREAL
from src.utils.RESOURCES import FISH
from src.utils.RESOURCES import FLOWER
from src.utils.RESOURCES import RESOURCES
from src.utils.RESOURCES import ORE
from src.utils.RESOURCES import WOOD

Xelorium = {
	'4,-6': Square(x=4, y=-6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, '4,-5', None], resources=[], specialSquares=[]),
	'4,-5': Square(x=4, y=-5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,-6', '5,-5', '4,-4', '3,-5'], resources=[], specialSquares=[]),
	'4,-4': Square(x=4, y=-4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,-5', '5,-4', '4,-3', '3,-4'], resources=[], specialSquares=[]),
	'4,-3': Square(x=4, y=-3, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,-4', None, None, '3,-3'], resources=[], specialSquares=[]),
	'4,-1': Square(x=4, y=-1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, '4,0', None], resources=[], specialSquares=[]),
	'4,0': Square(x=4, y=0, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,-1', '5,0', '4,1', '3,0'], resources=[], specialSquares=[]),
	'4,1': Square(x=4, y=1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,0', '5,1', '4,2', '3,1'], resources=[], specialSquares=[]),
	'4,2': Square(x=4, y=2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,1', None, None, '3,2'], resources=[], specialSquares=[]),
	'4,4': Square(x=4, y=4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, '4,5', None], resources=[], specialSquares=[]),
	'4,5': Square(x=4, y=5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,4', '5,5', '4,6', '3,5'], resources=[], specialSquares=[]),
	'4,6': Square(x=4, y=6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,5', '5,6', '4,7', '3,6'], resources=[], specialSquares=[]),
	'4,7': Square(x=4, y=7, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['4,6', None, None, '3,7'], resources=[], specialSquares=[]),
	'2,-5': Square(x=2, y=-5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '3,-5', '2,-4', None], resources=[], specialSquares=[]),
	'2,-4': Square(x=2, y=-4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['2,-5', '3,-4', '2,-3', '1,-4'], resources=[], specialSquares=[]),
	'2,-3': Square(x=2, y=-3, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['2,-4', '3,-3', None, '1,-3'], resources=[], specialSquares=[]),
	'2,0': Square(x=2, y=0, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '3,0', '2,1', None], resources=[], specialSquares=[]),
	'2,1': Square(x=2, y=1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['2,0', '3,1', '2,2', '1,1'], resources=[], specialSquares=[]),
	'2,2': Square(x=2, y=2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['2,1', '3,2', None, '1,2'], resources=[], specialSquares=[]),
	'2,5': Square(x=2, y=5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '3,5', '2,6', None], resources=[], specialSquares=[]),
	'2,6': Square(x=2, y=6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['2,5', '3,6', '2,7', '1,6'], resources=[], specialSquares=[]),
	'2,7': Square(x=2, y=7, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['2,6', '3,7', None, '1,7'], resources=[], specialSquares=[]),
	'7,-7': Square(x=7, y=-7, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'7,-2': Square(x=7, y=-2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'7,3': Square(x=7, y=3, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'1,-4': Square(x=1, y=-4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '2,-4', '1,-3', None], resources=[], specialSquares=[]),
	'1,-3': Square(x=1, y=-3, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['1,-4', '2,-3', '1,-2', None], resources=[], specialSquares=[]),
	'1,-2': Square(x=1, y=-2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['1,-3', None, None, '0,-2'], resources=[], specialSquares=[]),
	'1,1': Square(x=1, y=1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '2,1', '1,2', None], resources=[], specialSquares=[]),
	'1,2': Square(x=1, y=2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['1,1', '2,2', None, None], resources=[], specialSquares=[]),
	'1,6': Square(x=1, y=6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '2,6', '1,7', None], resources=[], specialSquares=[]),
	'1,7': Square(x=1, y=7, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['1,6', '2,7', None, None], resources=[], specialSquares=[]),
	'0,-5': Square(x=0, y=-5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'0,-2': Square(x=0, y=-2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '1,-2', None, None], resources=[], specialSquares=[]),
	'0,0': Square(x=0, y=0, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'0,3': Square(x=0, y=3, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'0,5': Square(x=0, y=5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'0,8': Square(x=0, y=8, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'3,-5': Square(x=3, y=-5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '4,-5', '3,-4', '2,-5'], resources=[], specialSquares=[]),
	'3,-4': Square(x=3, y=-4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['3,-5', '4,-4', '3,-3', '2,-4'], resources=[], specialSquares=[]),
	'3,-3': Square(x=3, y=-3, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['3,-4', '4,-3', None, '2,-3'], resources=[], specialSquares=[]),
	'3,0': Square(x=3, y=0, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '4,0', '3,1', '2,0'], resources=[], specialSquares=[]),
	'3,1': Square(x=3, y=1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['3,0', '4,1', '3,2', '2,1'], resources=[], specialSquares=[]),
	'3,2': Square(x=3, y=2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['3,1', '4,2', None, '2,2'], resources=[], specialSquares=[]),
	'3,5': Square(x=3, y=5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, '4,5', '3,6', '2,5'], resources=[], specialSquares=[]),
	'3,6': Square(x=3, y=6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['3,5', '4,6', '3,7', '2,6'], resources=[], specialSquares=[]),
	'3,7': Square(x=3, y=7, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['3,6', '4,7', None, '2,7'], resources=[], specialSquares=[]),
	'6,-6': Square(x=6, y=-6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'6,-4': Square(x=6, y=-4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, '5,-4'], resources=[], specialSquares=[]),
	'6,-1': Square(x=6, y=-1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'6,1': Square(x=6, y=1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, '5,1'], resources=[], specialSquares=[]),
	'6,4': Square(x=6, y=4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'6,6': Square(x=6, y=6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, '5,6'], resources=[], specialSquares=[]),
	'5,-5': Square(x=5, y=-5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, '5,-4', '4,-5'], resources=[], specialSquares=[]),
	'5,-4': Square(x=5, y=-4, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['5,-5', '6,-4', None, '4,-4'], resources=[], specialSquares=[]),
	'5,-2': Square(x=5, y=-2, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, None, None], resources=[], specialSquares=[]),
	'5,0': Square(x=5, y=0, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, '5,1', '4,0'], resources=[], specialSquares=[]),
	'5,1': Square(x=5, y=1, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['5,0', '6,1', None, '4,1'], resources=[], specialSquares=[]),
	'5,5': Square(x=5, y=5, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=[None, None, '5,6', '4,5'], resources=[], specialSquares=[]),
	'5,6': Square(x=5, y=6, dofusMap=DofusMap.XELORIUM, city="Astrub", place="", adjs=['5,5', '6,6', None, '4,6'], resources=[], specialSquares=[]),
}